[package]
name = "example-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_dispatch = { git = "https://github.com/jbirnick/serde-dispatch" }
clap = { version = "4.5", features = ["derive"] }
